#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage : sh 03 \"Name of the movie\"."
	exit 1
else
	API_KEY=$(echo "e67ed67662191f052ce9a89e1539a636")
	NAME=$(echo "$1" | sed 's/ /%20/g')
	VAR=$(curl -s https://api.themoviedb.org/3/search/movie\?api_key\=$API_KEY\&language\=fr-FR\&query\=$NAME\&page\=1\&include_adult\=false)
	IDS=$(curl -s https://api.themoviedb.org/3/genre/movie/list?api_key=658767fbd68eea723024c351086861e5)
	IDS_G=$(echo $IDS | sed 's/{/\\n/g' | sed 's/"/ /g' | sed 's/ },//g' | sed 's/ id ://g' | sed 's/, name //g')
	GREP=$(echo -e "$VAR\n" | sed 's/,"/\\n/g' | sed 's/"//g')
	echo $GREP | grep -m 1 "original_title:" | sed 's/original_title/Titre VO/' | sed 's/:/: 		/'
	echo $GREP | grep -A 2 "original_title" | sed -n 3p | sed 's/:/:/' | sed 's/:/:		/' | sed 's/title/Titre VF/'
	RATE=$(echo $GREP | grep -m 1 "vote_average:" | sed 's/vote_average/Note (imdb)/' | sed 's/:/: 		/')
	echo "$RATE/10"
	echo $GREP | grep -m 1 "release_date:" | sed 's/release_date/Date de sortie/' | cut -d '}' -f1 | sed 's/:/:		/'
	IDS_V=$(echo $GREP | grep -m 1 "genre_ids:" | sed 's/genre_ids://' | cut -d '}' -f1 | sed 's/\[//' | sed 's/\]//' | sed 's/,/ /g')
	GENRE=$(echo "")
	GENRE1=$(echo $IDS_V | cut -d ' ' -f1)
	GENRE2=$(echo $IDS_V | cut -d ' ' -f2)
	GENRE3=$(echo $IDS_V | cut -d ' ' -f3)
	GENRE4=$(echo $IDS_V | cut -d ' ' -f4)
	GENRE5=$(echo $IDS_V | cut -d ' ' -f5)
	if [ ! -z $GENRE1 ]
	then
		GENRE1=$(echo $IDS_G | grep $GENRE1 | cut -d' ' -f2)
		GENRE=$(echo $GENRE $GENRE1 | sed 's/+/		/')
	fi
	if [ ! -z $GENRE2 ]
	then
		GENRE=$(echo $GENRE ", " | sed 's/ , /, /')
		GENRE2=$(echo $IDS_G | grep $GENRE2 | cut -d' ' -f2)
		GENRE=$(echo $GENRE $GENRE2)
	fi
	if [ ! -z $GENRE3 ]
	then
		GENRE=$(echo $GENRE ", " | sed 's/ , /, /')
		GENRE3=$(echo $IDS_G | grep $GENRE3 | cut -d' ' -f2)
		GENRE=$(echo $GENRE $GENRE3)
	fi
	if [ ! -z $GENRE4 ]
	then
		GENRE=$(echo $GENRE ", " | sed 's/ , /, /')
		GENRE4=$(echo $IDS_G | grep $GENRE4 | cut -d' ' -f2)
		GENRE=$(echo $GENRE $GENRE4)
	fi
	if [ ! -z $GENRE5 ]
	then
		GENRE=$(echo $GENRE ", " | sed 's/ , /, /')
		GENRE5=$(echo $IDS_G | grep $GENRE5 | cut -d' ' -f2)
		GENRE=$(echo $GENRE $GENRE5)
	fi
	echo "Genre(s):		"$GENRE
	echo $GREP | grep -m 1 "overview:"| sed "s/overview/Synopsis/" | sed "s/:/: /"
fi
